config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :profiles
  devise_for :users
  root 'home#welcome'

  get '/home', to: 'home#index'

  get '/verify', to: 'home#verify'
  patch '/verify', to: 'home#confirm_verify'
  delete '/verify', to: 'home#delete_verify'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :posts

  mount_uploader :image, ImageUploader
  validates :image, file_size: { less_than: 1.megabytes }

  def badge
    self.tier ? "#{self.tier.downcase}_badge.png" : 'unranked_badge.png'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  # Include default devise modules. Others available are:
  #   :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:summoner_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  before_action :authenticate_user!, except: [:welcome]

  def welcome
    unless current_user
      redirect_to new_user_session_path
      return
    end

    @user = current_user
    if @user.profile
      redirect_to home_path
    elsif @user
      # generate_key
      @profile = Profile.create(verification_key: 'soloq09caef7a')
      @user.profile = @profile
    else
      redirect_to new_user_session_path
    end
  end

  def index
    @posts = Post.order('created_at DESC, id DESC').page(params[:page]).per(10)
    @post = Post.new
  end

  def verify
    @user = current_user
    @profile = @user.profile
    @key = @profile.verification_key
  end

  def confirm_verify
    summoner = params[:profile][:name]
    @user = current_user
    @profile = @user.profile
    @key = @profile.verification_key

    summoner_id_name = get_summoner_id_name(summoner)
    unless @key == get_summoner_verification_code(summoner_id_name[0])
      redirect_to verify_path, notice: 'Verification failed.'
      return
    end

    @profile.lol_id = summoner_id_name[0]
    @profile.name = summoner_id_name[1]
    if @profile.save
      update_rank(@profile)
      redirect_to root_path, notice: 'Changes saved!'
    else
      redirect_to verify_path, notice: 'Failed to save.'
    end
  end

  def delete_verify
    @user = current_user
    @profile = @user.profile
    @profile.name = nil
    @profile.lol_id = nil
    @profile.rank = nil
    @profile.tier = nil
    if @profile.save
      redirect_to verify_path, notice: 'Summoner desvinculado com sucesso.'
    else
      redirect_to verify_path, notice: 'Alguma coisa deu errado.'
    end
  end

  private

  def update_rank(profile)
    tier_rank = get_user_tier_rank(profile)
    profile.tier = tier_rank[0]
    profile.rank = tier_rank[1]
    profile.save
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.profile_id = current_user.profile.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :profile_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :tier, :rank, :image, :lol_id, :verification_key, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  require 'securerandom'
  require 'open-uri'

  def generate_key
    "soloq#{SecureRandom.hex(4)}"
  end

  def get_summoner_id_name(summoner_name)
    name = summoner_name.gsub(' ', '%20')
    by_name = open("https://br1.api.riotgames.com/lol/summoner/v3/summoners/by-name/#{name}?api_key=#{ENV["RIOT_KEY"]}").string

    summoner_hash = JSON.parse by_name
    [summoner_hash["id"], summoner_hash["name"]]
  end

  def get_summoner_verification_code(summoner_id)
    by_id = open("https://br1.api.riotgames.com/lol/platform/v3/third-party-code/by-summoner/#{summoner_id}?api_key=#{ENV["RIOT_KEY"]}").string

    verification_hash = JSON.parse by_id
  end

  def get_user_tier_rank(profile)
    rank_string = open("https://br1.api.riotgames.com/lol/league/v3/positions/by-summoner/#{profile.lol_id}?api_key=#{ENV["RIOT_KEY"]}").string

    rank_array = JSON.parse rank_string

    tier = 'UNRANKED'
    rank = nil
    rank_array.each do |queue_hash|
      next unless queue_hash["queueType"] == "RANKED_SOLO_5x5"
      tier = queue_hash["tier"]
      rank = queue_hash["rank"]
    end

    [tier, rank]
  end
end

# dummy ID
# 1350198
# dummy key
# soloq09caef7a

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<h1>SoloQ</h1>

  <%= render 'posts/form', post: @post %>

<div id="posts">
  <%= render @posts %>
</div>

<%= link_to_next_page @posts, 'Load More', :remote => true, :id=>"load_more_link" %>

app/views/home/index.js.erb
$('#posts').append("<%= escape_javascript(render :partial => @posts)%>");
$('#load_more_link').replaceWith("<%= escape_javascript(link_to_next_page(@posts, 'Load More', :remote => true, :id=>'load_more_link'))%>");

app/views/home/verify.html.erb
<h1>Vincular Summoner</h1>

<% if @profile.name %>
  <p>
    Summoner atualmente vinculado: <strong><%= @profile.name %></strong>
    <span class="badge badge-secondary"><%= @profile.tier %> <%= @profile.rank %></span>
    <br>
  </p>

  <p>Caso queira vincular um summoner diferente, basta refazer o processo.</p>
  <br>
<% end %>

Código: <%= @key %>

<%= form_for @profile, url: {action: 'confirm_verify'} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit 'Vincular', class: 'btn btn-primary' %>
<% end %>

<br>

<%= image_tag 'verify_guide2.jpg', id: 'verify_guide' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoloQ</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="wrapper">

      <!-- Sidebar -->
      <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
          <li class="sidebar-brand">
            <%= link_to 'SoloQ', root_path %>
          </li>
          <li>
            <%= link_to 'Home', root_path %>
          </li>

          <% if current_user %>
            <li>
              <%= link_to 'Vincular Summoner', verify_path %>
            </li>
            <% if current_user.profile %>
              <li>
                <%= link_to 'Meu Perfil', profile_path(current_user.profile) %>
              </li>
            <% end %>
          <% end %>
          <li>
            <% unless current_user %>
              <%= link_to 'Login', new_user_session_path %>
            <% end %>
          </li>
        </ul>
      </div>
      <!-- /#sidebar-wrapper -->

      <!-- Page Content -->
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">T</a>

          <% if current_user %>
            <%= current_user.email %> -
            <%= current_user.profile.name %> -
            <%= current_user.profile.lol_id %> -
            <%= current_user.profile.tier %>
            <%= current_user.profile.rank %> -
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'Login', new_user_session_path %>
          <% end %>

          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>


          <div class="container" id="main">
            <%= yield %>
          </div>
        </div>
      </div>
      <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit 'Postar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post row align-items-start">

  <%= link_to profile_path(post.profile), class: 'post-face-box' do %>
    <%= image_tag post.profile.image.url, class: 'post-face' %>
  <% end %>

  <div class="post-body">
    <strong><%= link_to post.profile.name, profile_path(post.profile) %></strong>
    <%= image_tag post.profile.badge, size: '30x30' %>
    <span class="badge badge-secondary"><%= post.profile.tier %> <%= post.profile.rank %></span>
    <span><%= post.created_at.strftime("%b %d, %Y %H:%M") %></span>
    <p><%= post.body %></p>
  </div>
  <% if post.profile == current_user.profile %>
    <%= link_to 'x', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.body %></td>
        <td><%= post.profile %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @post.profile %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :profile_name %>
  </div>

  <div class="field">
    <%= form.label :tier %>
    <%= form.text_field :tier, id: :profile_tier %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.text_field :rank, id: :profile_rank %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :profile_image %>
  </div>

  <div class="field">
    <%= form.label :lol_id %>
    <%= form.text_field :lol_id, id: :profile_lol_id %>
  </div>

  <div class="field">
    <%= form.label :verification_key %>
    <%= form.text_field :verification_key, id: :profile_verification_key %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :profile_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tier</th>
      <th>Rank</th>
      <th>Image</th>
      <th>Lol</th>
      <th>Verification key</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.tier %></td>
        <td><%= profile.rank %></td>
        <td><%= profile.image %></td>
        <td><%= profile.lol_id %></td>
        <td><%= profile.verification_key %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div id="profile-name">
  <%= image_tag @profile.image.url, size: '150x150', id: 'display-picture' %>
  <h2><%= @profile.name %></h2>
  <p><%= @profile.tier.capitalize %> <%= @profile.rank %></p>
  <%= image_tag @profile.badge, size: '30x30' %>
</div>

<div id="profile-posts">
  <%= render @profile.posts %>
</div>

<div id="profile-controls">
  <% if current_user == @profile.user %>
    <%= link_to 'Edit', edit_profile_path(@profile) %>
  <% end %>
</div>